#!/usr/bin/env python3
import os
import sys

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

question = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Hello GPT-5!"

response = client.chat.completions.create(
    model="gpt-5", messages=[{"role": "user", "content": question}]
)

print(response.choices[0].message.content)
